Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,48 +1,38 @@
 name: oidc-poc
 on:
-    push:
-        branches:
-            - '*'
+  push:
+    branches:
+      - '*'
 jobs:
-    auth:
-        permissions:
-            contents: read
-            id-token: write
-        runs-on: ubuntu-latest
-        steps:
-            - name: Get id token
-              run: |
-                    ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
-                    "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
-                    echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
+  auth:
+    permissions:
+      contents: read
+      id-token: write
+    runs-on: ubuntu-latest
+    steps:
+      - name: Get id token
+        run: |
+          ID_TOKEN=$(curl -sLS -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
+          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=jfrog-github" | jq .value | tr -d '"')
+          echo "ID_TOKEN=${ID_TOKEN}" >> $GITHUB_ENV
 
-            - name: Exchange token with access
-              env:
-                    ID_TOKEN: ${{env.ID_TOKEN}}
-                    JFROG_PLATFORM_URL: https://hts2.jfrog.io
-              run: |
-                    ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"ashritha\"}" | jq .access_token | tr -d '"')
-                    echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
+      - name: Exchange token with access
+        env:
+          ID_TOKEN: ${{ env.ID_TOKEN }}
+          JFROG_PLATFORM_URL: https://hts2.jfrog.io
+        run: |
+          ACCESS_TOKEN=$(curl -XPOST -H "Content-Type: application/json" "https://hts2.jfrog.io/access/api/v1/oidc/token" -d "{\"grant_type\": \"urn:ietf:params:oauth:grant-type:token-exchange\", \"subject_token_type\":\"urn:ietf:params:oauth:token-type:id_token\", \"subject_token\": \"${ID_TOKEN}\", \"provider_name\": \"ashritha\"}" | jq .access_token | tr -d '"')
+          echo "ACCESS_TOKEN=${ACCESS_TOKEN}" >> $GITHUB_ENV
 
-            - name: Install numpy from Artifactory
-              env:
-                    ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
-              run: |
-                    pip install --upgrade pip
-                    pip install numpy --no-deps --index-url "https://ashrithac:${ACCESS_TOKEN}@hts2.jfrog.io/artifactory/ashritha-pypi/simple"
-                    
-            # Set up the environment for installing the package
-            - name: Set up Python environment
-              uses: actions/setup-python@v2
-              with:
-                    python-version: '3.10'
+      - name: Fetch numpy package from JFrog
+        env:
+          ACCESS_TOKEN: ${{ env.ACCESS_TOKEN }}
+        run: |
+          pip install numpy --index-url "https://hts2.jfrog.io/artifactory/ashritha-pypi/simple?access_token=${ACCESS_TOKEN}" -vvv || {
+            echo "Failed to install numpy from JFrog. Falling back to PyPI..."
+            pip install numpy
+          }
 
-            # Install your package
-            - name: Install from setup.py
-              run: |
-                    pip install .
-
-            # Run your application or tests if needed
-            - name: Run tests
-              run: |
-                    python -m unittest discover -s tests
+      - name: Fetch file using the OIDC generated token
+        run: |
+          curl -H "Authorization: Bearer ${ACCESS_TOKEN}" -X GET https://hts2.jfrog.io/artifactory/api/storage/dev-pypi-local/my_vulnerable_project/0.1.0/my_vulnerable_project-0.1.0-py3-none-any.whl -vvv
